export const myPlaylist = [
    {
        title: "We Are",
        artist: "Alex M.O.R.P.H. & Paul van Dyk",
        src: "./my-playlist/Alex M.O.R.P.H. & Paul van Dyk - We Are.mp3"
    },
    {
        title: "Autumn",
        artist: "Ben Böhmer",
        src: "./my-playlist/Ben Böhmer - Autumn.mp3"
    },
    {
        title: "Dive (feat. Margret)",
        artist: "Ben Böhmer",
        src: "./my-playlist/Ben Böhmer - Dive (feat. Margret).mp3"
    },
    {
        title: "I Remember",
        artist: "Deadmau5, Kaskade",
        src: "./my-playlist/deadmau5, Kaskade - I Remember.mp3"
    },
    {
        title: "Dreamscape",
        artist: "009 Sound System",
        src: "./my-playlist/009 Sound System - Dreamscape.mp3"
    },
    {
        title: "Nothing but You",
        artist: "Paul van Dyk",
        src: "src/my-playlist/Paul van Dyk - Nothing but You (PvD radio mix).mp3"
    },
    {
        title: "White Lies",
        artist: "Paul van Dyk ft Jessica Sutta",
        src: "./my-playlist/Paul Van Dyk ft Jessica Sutta - White Lies.mp3"
    },
    {
        title: "Sleepwalking (1980s Chillwave Remix)",
        artist: "The Chain Gang of 1974",
        src: "./my-playlist/The Chain Gang of 1974 - Sleepwalking (1980s Chillwave Remix).mp3"
    },
    {
        title: "Intro",
        artist: "The XX",
        src: "src/my-playlist/The xx - Intro.mp3"
    }
];

// export default myPlaylist;